#pragma once

#define OFFSET_BETWEEN_PIPE_X 150
#define OFFSET_BETWEEN_PIPE_Y 240
#define PIPE_STARTING_OFFSET_X 400

#define FLOOR_HEIGHT 200

#define PIPE_WIDTH 150
#define PIPE_HEIGHT 420

#define PLAYER_WIDTH 100
#define PLAYER_HEIGHT 100