#pragma once

#define OFFSET_BETWEEN_PIPE_X 150
#define OFFSET_BETWEEN_PIPE_Y 240
#define PIPE_STARTING_OFFSET_X 400

#define FLOOR_WIDTH 333.0f
#define FLOOR_HEIGHT 200.0f

#define PIPE_WIDTH 150.0f
#define PIPE_HEIGHT 420.0f

#define PLAYER_WIDTH 80.0f
#define PLAYER_HEIGHT 60.0f

#define PLATFORM_MOVING_SPEED -4.0f
#define PLAYER_MASS 2.0f
#define GRAVITY_FORCE 2.0f